id: IADC82D2A
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:08:00.285494+00:00
last_modified: 2022-12-14 18:08:00.285502+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-07-23T01:58:33.491Z'
  creationid: dirk
  eft-text-id: UT22084-061-013
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_193-The_Prophecy_of_Sri_Mahadevi-v1
bases:
  D39A:
    source_metadata: null
    order: 1
    base_file: D39A.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
